sudo: required
dist: bionic

language: go

go:
  - 1.12.x

services:
  - docker

env:
  global:
    - DOCKER_PLATFORMS="linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8"
    - APP_FOLDER=/go/src/github.com/moikot/slack-nil-bot/

git:
  depth: 1

before_install:
  - go get github.com/mattn/goveralls

script:
  # Restore packages using moikot/golang-dep
  - >-
    docker run --rm -v $(pwd):${APP_FOLDER} -w ${APP_FOLDER}
    -u $(id -u ${USER}):$(id -g ${USER})
    moikot/golang-dep ensure -vendor-only
  # Run all the tests and report the coverage
  - go test -covermode=count -coverprofile=profile.cov -coverpkg=./... ./...
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci

before_deploy:
  # Update docker to the latest version, enable experimental mode, enable BuildKit
  - echo '{"experimental":true,"features":{"buildkit":true}}' | sudo tee /etc/docker/daemon.json
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  # Get scripts for building multi-architectural Docker images and manifests
  - id=$(docker create moikot/mua-docker-tools)
  - docker cp $id:/scripts.sh /tmp/mua-scripts.sh
  - docker rm -v $id

deploy:
  provider: script
  script: >-
    bash -c "/tmp/mua-scripts.sh build_images
    ${TRAVIS_REPO_SLUG} ${TRAVIS_TAG} ${DOCKER_PLATFORMS}
    --build-arg APP_FOLDER=${APP_FOLDER} &&
    /tmp/mua-scripts.sh push_images
    ${TRAVIS_REPO_SLUG} ${TRAVIS_TAG} ${DOCKER_PLATFORMS}
    ${DOCKER_USERNAME} ${DOCKER_PASSWORD} &&
    /tmp/mua-scripts.sh push_readme
    ${TRAVIS_REPO_SLUG} README.md
    ${DOCKER_USERNAME} ${DOCKER_PASSWORD}"
  on:
    tags: true

notifications:
  email: false
