dist: bionic
os: linux
language: shell

language: go

go:
  - 1.12.x

services:
  - docker

env:
  global:
    - DOCKER_PLATFORMS="linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6"
    - APP_FOLDER=/go/src/github.com/moikot/slack-nil-bot/

git:
  depth: 1

before_install:
  - go get github.com/mattn/goveralls

script:
  # Restore packages using moikot/golang-dep
  - >-
    docker run --rm -v $(pwd):${APP_FOLDER} -w ${APP_FOLDER}
    -u $(id -u ${USER}):$(id -g ${USER})
    moikot/golang-dep ensure -vendor-only
  # Run all the tests and report the coverage
  - go test -covermode=count -coverprofile=profile.cov -coverpkg=./... ./...
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci

before_deploy:
  # Get scripts for building Docker images
  - id=$(docker create moikot/docker-tools)
  - docker cp $id:/scripts.sh /tmp/scripts.sh && docker rm -v $id
  # Update docker to the latest version and enable BuildKit
  - /tmp/scripts.sh update_docker

deploy:
  provider: script
  script: >-
    bash -c "echo "${DOCKER_PASSWORD}" |
    docker login -u "${DOCKER_USERNAME}" --password-stdin &&
    /tmp/scripts.sh build_images
    ${TRAVIS_REPO_SLUG} ${TRAVIS_TAG} ${DOCKER_PLATFORMS}
    --push --build-arg APP_FOLDER=${APP_FOLDER} &&
    /tmp/scripts.sh push_readme
    ${TRAVIS_REPO_SLUG} README.md
    ${DOCKER_USERNAME} ${DOCKER_PASSWORD}"
  on:
    tags: true
    condition: tag =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/

notifications:
  email: false
